segmentation:
  model_path: "flax_models/segmentation.params"
  hidden_size: 256
  max_len: 90

translation:
  model_path: "flax_models/translation.params"
  vocab_path: "flax_models/vocab.json"
  hidden_size: 256
  max_input_len: 40
  max_output_len: 40
  
embedding_size: 128 # Output size of palmtree